# Generated by Django 3.0.6 on 2020-05-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photography',
            name='height',
        ),
        migrations.RemoveField(
            model_name='photography',
            name='width',
        ),
        migrations.AlterField(
            model_name='photography',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user/%Y/%m/%d/'),
        ),
    ]
