# Generated by Django 3.0.6 on 2020-05-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_profile', '0002_auto_20200513_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='photo',
            field=models.ImageField(upload_to='user/%Y/%m/%d/'),
        ),
    ]
